version: '2.3'
services:

  drupal9-test-server:
    image: nginx:1.19
    ports:
    - 80:80
    - 443:443
    volumes:
    - .:/var/www/drupal9-test
    - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - drupal9-test-php

  drupal9-test-php:
    image: pontifex/php7.4-fpm:latest
    volumes:
    - .:/var/www/drupal9-test
    - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    - ./docker/php/mods/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    links:
    - drupal9-test-db
    depends_on:
    - drupal9-test-db

  drupal9-test-db:
    container_name: db
    image: mysql:5.7
    volumes:
      - "~/.drupal9-test/db:/var/lib/mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "4306:3306"
      - "3306:3306"
